[[upgrading]]
= Upgrading
:toc: right

== Guillotine application

IMPORTANT: Guillotine version 7 is required if you need to modify graphql schema in your application.

== Upgrading from v2.x

. You need to use Next.js app router to be able to use v3.x.
See https://nextjs.org/docs/pages/building-your-application/upgrading/app-router-migration[upgrade instructions] from pages router here.

. `_renderable` page is now an API route at `src/api/renderable/route.ts`.

. `@enonic/nextjs-adapter` methods renamed:
+
getLocaleProjectConfig() -> getProjectLocaleConfig()
+
getProjectLocaleConfigById -> getProjectLocaleConfigById()

. `@enonic/nextjs-adapter` exports rearranged:
+
Most of the exports are now available from `@enonic/nextjs-adapter` package root.
Client-only exports are available from `@enonic/nextjs-adapter/client` package.
Views are available under `@enonic/nextjs-adapter/views/<ViewName>`.

. `ENONIC_PROJECTS` env var syntax change:
+
.Language is now required for every project config:

    ENONIC_PROJECTS=<lang>:<repo-name>/site/path[,<lang>:<repo-name>/site/path,...]
+
TIP: First config in the list is used as default.
+
. `next.config.js` config changes:
+
.Remove i18n block from next.js config:
[source,language="javascript"]
----
i18n: {
    locales: ['en', 'no'],
    defaultLocale: 'en',
}
----
+
.Add phrases block to webpack config:
[source,language="javascript"]
----
config.resolve.alias = {
    ...config.resolve.alias,
    "@phrases": path.resolve(__dirname, "./src/phrases"),
}
----

. *Add* `src/phrases` folder to your project root.
This folder should contain static translations for every language from `ENONIC_PROJECTS` env var in the following format: `src/phrases/<lang>.json`

    src/phrases/en.json
    src/phrases/no.json

. Middleware file has been updated to support new i18n config.
If you have custom middleware, you need to update it to support new i18n config.
