= Release Notes
:toc: right

== Next.XP Demo 2

=== Support for shortcuts

Next.XP now supports base:shortcut content types.
Note, that shortcuts are not displayed in Page Editor because there is nothing to edit.

=== Support Next.js localization

You can now use multi-language Next.js projects with Next.XP, both in Content Studio and stand-alone.
All that is needed for that, on top of the `i18n` section in `next.config.js`, is installing `guillotine` application (if you don't have it already) and adding a new environmental variable called `ENONIC_PROJECTS`.
You can read more in the <<upgrading, upgrade section>>.

=== Changes to nextjs url/secret configuration

There is no more url and secret inputs in the next.xp application configuration.
Instead, there is a dropdown allowing to select named configuration from the app-nextxp configuration file.
Format of that file has also been changed to support that.

=== Other improvements

* Static generation for every locale

* Static paths query is non-recursive now and queries all content in one request per-repository

* You can configure different site names for different locales

* All environmental variabales now have `ENONIC_` prefix to avoid collisions
