= Page cache and revalidation
:toc: right
:imagesdir: media/

In this chapter you will learn about NextJS' static pages and how the Enonic triggers re-generation of pages when publishing.

== Introduction
The NextJS front-end is configured to use static page generation (ISR), which basically means you get lightning fast pages, but also with specific limitations, such as getting new pages and changes instantly live on your site.

TIP: NextJS also supports Server Side Rendering (SSR) which can be enabled by modifying the `[[...contentPath]].tsx` page handler.

== Prod mode
So far, you have been running NextJS in dev mode.

By starting NextJS in `prod` mode, the application is automatically optimized, and in our case, pages get rendered statically at compile time.

== Task: Activate prod mode

TIP: Remember to stop your existing NextJS dev instance before you continue.

. **Start NextJS in prod mode**:
+
    npm run prod
+
This will take a while longer as when compared to dev mode.

. **Verify** by pointing your browser to http://localhost:4242[http://localhost:4242^], you should now see the published items, just like in dev mode. **Sweet!**


== Task: Update the connector

With NextJS now running on a different port, the preview integration we configured earlier has been broken.

. **Fix the preview** by updating the NextJS app configuration on your site with the new URL, and confirm that preview starts working again.

TIP: Content Studio uses NextJS' preview mode, and will bypass static pages, so you should always see the latest updates to your drafts instantly.


== Task: Test page invalidation

. **Edit your front-page, and publish the changes** to trigger a revalidation hook.

Despite running static pages, the page should get updated at `http://localhost:4242` with your latest changes - more or less instantly. 🎉

How does it work? The Next.js application on your site is already connected to the front-end, and automatically triggers the revalidation of all pages when it detects the publishing event.

NOTE: You should also be able to tell from the NextJS log that the revalidation was triggered.

With prod mode and revalidation sorted out, its about time you <<deployment#, deploy your apps to live servers>>.