= Static Site Generation
:toc: right
:imagesdir: media/
:sourcedir: ../src/app/[locale]/[[...contentPath]]/

In this chapter you will learn about NextJS' static site generation capabilities, and how Enonic triggers re-generation of pages when publishing.

== Introduction

Your NextJS front-end strives to use Static Site Generation (SSG) when possible which basically means you get lightning fast pages, but adds an additional compilation build step.

For more information visit the https://nextjs.org/docs/app/building-your-application/rendering[Next.js rendering documentation].

== Task: Activate prod mode

So far, you have been running Next.js in dev mode.

By starting Next.js in `prod` mode, the application is automatically optimized, and in our case, pages get pre-rendered statically before the server starts.

TIP: Remember to stop your existing Next.js dev instance before you continue.

. **Start Next.js in prod mode**:
+
    npm run prod
+
This will take a while longer as when compared to dev mode.

. **Verify** by pointing your browser to http://localhost:4242[http://localhost:4242^], you should now see the published items, just like in dev mode. Only this time, they will be much faster. **Sweet!**


== Task: Fixing preview

With Next.js now running on a different port, Content Studio preview will stop working.

. Fix the preview by *adding a Next.XP configuration file*, with the following content to your sandbox:
+
NOTE: The configuration files are located in your sandbox home directory, which can be found in your users home directory as `.enonic/sandboxes/<your-sandbox>/home/config/`. 
+
.com.enonic.app.nextxp.cfg
[source,properties]
----
nextjs.default.secret=mySecretKey
nextjs.default.url=http://127.0.0.1:4242
----

. *Verify that the preview is working* in Content Studio.
+
TIP: Content Studio uses Next.js' preview mode, which automatically bypasses static pages - giving you a fresh preview of your draft content.

== Task: Test page invalidation
With all pages now being cached as files, Next.js must be instructed to re-generate the pages when a change is published.

*Edit your front-page, and publish the changes*.
This will trigger a revalidation hook, which is built into the Next.XP app.

The page should now get updated at `http://localhost:4242` - more or less instantly.🎉

=== What happened?

In addition to handling previews, the Next.XP app automatically triggers revalidation of all pages when it detects the publishing event.

NOTE: You should also be able to tell from the Next.js log that the revalidation was triggered.

== A look at the code

Static Site Generation is controlled within the content page handler.

And the function we are interested the most is:

* `generateStaticParams()` - This function will be used by Next.js at build time to create a list of pages to compile before the server starts.

Below, we explain the details of the code:

.src/app/[locale]/[[...contentPath]]/page.ts
[source,TypeScript,options="nowrap"]
----
include::{sourcedir}/page.tsx[]
----

As you can see, Next.XP provides methods to create static pages, but the best part is that it chooses the best rendering and caching scheme based on what your code is doing !

With prod mode and revalidation sorted out, let's see how to add <<i18n#, multi-language>> support.
